DEFINE VARIABLE i AS INTEGER NO-UNDO.
DEFINE VARIABLE myArray AS DECIMAL NO-UNDO EXTENT 10.

DO i = 0 TO 9:
    ASSIGN myArray[i] = i + 0.5.
END.

DO i = 1 TO 10:
    DISPLAY myArray[i] FORMAT "9.9" SKIP.
END.