DEFINE VARIABLE myInt AS INTEGER NO-UNDO INITIAL 10.
DEFINE VARIABLE myDecimal AS DECIMAL NO-UNDO INITIAL 3.14.
DEFINE VARIABLE myChar AS CHARACTER NO-UNDO INITIAL 'Progress'.
DEFINE VARIABLE myDate AS DATE NO-UNDO INITIAL TODAY.
DEFINE VARIABLE myLogical AS LOGICAL NO-UNDO INITIAL TRUE.

DISPLAY myInt myDecimal myChar myDate myLogical.